# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet/releases/download/0.0.7/epithet_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "1930004418b6a99b18089005573f4ed485f840071c7cf4b4abc1caf687ad0e88"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/0.0.7/epithet_0.0.7_Linux_x86_64.tar.gz"
      sha256 "686143dad9da86ece918af8196f681e15d1d2e94dc9007346f20f555c8ed7f17"
    end
  end

  def install
    bin.install "epithet-agent"
    bin.install "epithet-auth"
    bin.install "epithet-ca"
  end

  def caveats; <<~EOS
    Installs the binaries, but no configs
  EOS
  end

  test do
    system "#{bin}/epithet-agent --version"
  end
end
