# This file was generated by GoReleaser. DO NOT EDIT.
class EpithetOidc < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet-oidc/releases/download/v0.0.5/epithet-oidc_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "08103654f801dd8b7c56e6cafbf74e9b8d90b3fb9256e4f94d976f39df95a071"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet-oidc/releases/download/v0.0.5/epithet-oidc_0.0.5_Linux_x86_64.tar.gz"
      sha256 "c5487515d764e4fd7eb69cda6e65dd6154b580a44dcb2f44191e1ae5ba006bb5"
    end
  end

  def install
    bin.install "epithet-oidc-plugin"
    bin.install "epithet-oidc-policy"
  end

  def caveats; <<~EOS
    Installs the binaries, but no configs
  EOS
  end

  test do
    system "#{bin}/epithet-oidc-plugin -h"
  end
end
