# This file was generated by GoReleaser. DO NOT EDIT.
class EpithetOidc < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet-oidc/releases/download/0.0.2/epithet-oidc_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "841bdad0db41dd81c4cf6db716a1d9b4cae1308eb83ae40c0c61247678afe739"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet-oidc/releases/download/0.0.2/epithet-oidc_0.0.2_Linux_x86_64.tar.gz"
      sha256 "d53cbd499d63fff81c58d2cd8f6f6ee01de39eac95d8e7858a9c487a7f877dd6"
    end
  end

  def install
    bin.install "epithet-oidc-plugin"
  end

  def caveats; <<~EOS
    some instructions
  EOS
  end

  test do
    system "#{bin}/epithet-oidc-plugin --version"
  end
end
