# This file was generated by GoReleaser. DO NOT EDIT.
class EpithetOidc < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet-oidc/releases/download/v0.0.4/epithet-oidc_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "03ce3b92c2c3bf1eefb3f3218628eb82ada3655b4042f04f3b635c018e6142a8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet-oidc/releases/download/v0.0.4/epithet-oidc_0.0.4_Linux_x86_64.tar.gz"
      sha256 "82ef9c43ba20ca27e6285012ffed99cede60fb84053133fe87f89cfc3e77e64c"
    end
  end

  def install
    bin.install "epithet-oidc-plugin"
    bin.install "epithet-oidc-policy"
  end

  def caveats; <<~EOS
    Installs the binaries, but no configs
  EOS
  end

  test do
    system "#{bin}/epithet-oidc-plugin -h"
  end
end
