# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet/releases/download/v0.0.11/epithet_0.0.11_Darwin_x86_64.tar.gz"
    sha256 "69db697ea621bcc7babe7bfe00580097bfbb250e39d4ea099bebf27b37850d0f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.0.11/epithet_0.0.11_Linux_x86_64.tar.gz"
      sha256 "f96d48fecaa7656703d0f24d7b18efa4c3973258d1b68e287737b60a499b4694"
    end
  end

  def install
    bin.install "epithet-agent"
    bin.install "epithet-auth"
    bin.install "epithet-ca"
  end

  def caveats; <<~EOS
    Installs the binaries, but no configs
  EOS
  end

  test do
    system "#{bin}/epithet-agent --version"
  end
end
