# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc ""
  homepage "https://epithet.io/"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/epithet-ssh/epithet/releases/download/0.0.4/epithet_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "2d391a34be92018495e144bb01f224ada6dfef0572ec8b0647dcf3d7f8dfc973"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/0.0.4/epithet_0.0.4_Linux_x86_64.tar.gz"
      sha256 "723c78def4dfae29c4f99946ea18f45eacd9c426dc6fe05a97d8eefcbb6f6430"
    end
  end

  def install
    bin.install "epithet-agent"
    bin.install "epithet-auth"
    bin.install "epithet-ca"
  end

  def caveats; <<~EOS
    some instructions
  EOS
  end

  test do
    system "#{bin}/epithet-agent --version"
  end
end
